BASE_URL = "https://www.saucedemo.com"
USERNAME_ID = "user-name"
PASSWORD_ID = "password"
LOGIN_BTN_ID = "login-button"
ERROR_MESSAGE_XPATH = "//*[@id='login_button_container']/div/form/div[3]/h3"
ITEM_CLASS_NAME = "inventory_item"
PRODUCT_XPATH = "/html/body/div/div/div/div[2]/div/div/div/div[1]/div[2]/div[2]/button"
SHOPPING_CART_XPATH = "//*[@id='shopping_cart_container']/a"
ITEM_TITLE = "Sauce Labs Backpack"
CART_ITEM_XPATH = "//*[@id='item_4_title_link']/div"